mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: org.oj.entity
  type-enums-package: org.oj.constant
  global-config:
    #驼峰下划线转换
#    db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    db-config:
      #主键类型  auto:数据库ID自增, input:用户输入ID, id_worker:全局唯一ID，Long类型的主键, id_worker_str:字符串全局唯一ID, uuid:全局唯一ID，UUID类型的主键, none:该类型为未设置主键类型
      id-type: input
      insert-strategy: NOT_EMPTY
      update-strategy: NOT_EMPTY
      where-strategy: NOT_EMPTY
      #逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    #一级缓存
    local-cache-scope: STATEMENT
    #二级缓存
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
